import {Portfolio, Project} from "../@types/domain.ts";

export const filterBtnLabelForPortfolio = [
  '전체', '문제해결 체험', '상상 더하기 체험', '웹툰 생성 체험', 'AI 간편 체험'
]
export const nowDeveloping =() => {
  alert('기능 개발 중 입니다.')
}
export const portfolioList:Portfolio[] = [
  {
    idx: 1,
    imgUrl: 'https://placehold.co/150',
    title: '강남구 미래인재 스마트시티',
    subtitle: '안전한 나의 친구',
    type: '문제해결 체험',
    user: 'ahnji1',
    timestamp: '2024-10-23',
    heartRate: 10,
  },
  {
    idx: 2,
    imgUrl: 'https://placehold.co/150',
    title: '강남구 미래인재 스마트시티',
    subtitle: '안전한 나의 친구',
    type: '문제해결 체험',
    user: 'ahnji1',
    timestamp: '2024-10-22',
    heartRate: 10,
  },
  {
    idx: 3,
    imgUrl: 'https://placehold.co/150',
    title: '강남구 미래인재 스마트시티',
    subtitle: '안전한 나의 친구',
    type: '문제해결 체험',
    user: 'ahnji1',
    timestamp: '2024-10-21',
    heartRate: 10,
  },
  {
    idx: 4,
    imgUrl: 'https://placehold.co/150',
    title: '강남구 미래인재 스마트시티',
    subtitle: '안전한 나의 친구',
    type: '문제해결 체험',
    user: 'ahnji1',
    timestamp: '2024-10-20',
    heartRate: 10,
  },
  {
    idx: 5,
    imgUrl: 'https://placehold.co/150',
    title: '강남구 미래인재 스마트시티',
    subtitle: '안전한 나의 친구',
    type: '문제해결 체험',
    user: 'ahnji1',
    timestamp: '2024-10-25',
    heartRate: 10,
  },
  {
    idx: 6,
    imgUrl: 'https://placehold.co/150',
    title: '강남구 미래인재 스마트시티',
    subtitle: '안전한 나의 친구',
    type: '문제해결 체험',
    user: 'ahnji1',
    timestamp: '2024-10-25',
    heartRate: 11,
  },
  {
    idx: 7,
    imgUrl: 'https://placehold.co/150',
    title: '강남구 미래인재 스마트시티',
    subtitle: '안전한 나의 친구',
    type: '문제해결 체험',
    user: 'ahnji1',
    timestamp: '2024-10-25',
    heartRate: 12,
  },
  {
    idx: 8,
    imgUrl: 'https://placehold.co/150',
    title: '강남구 미래인재 스마트시티',
    subtitle: '안전한 나의 친구',
    type: '문제해결 체험',
    user: 'ahnji1',
    timestamp: '2024-10-25',
    heartRate: 15,
  },
  {
    idx: 9,
    imgUrl: 'https://placehold.co/150',
    title: '강남구 미래인재 스마트시티',
    subtitle: '안전한 나의 친구',
    type: '문제해결 체험',
    user: 'ahnji1',
    timestamp: '2024-10-25',
    heartRate: 20,
  },
  {
    idx: 10,
    imgUrl: 'https://placehold.co/150',
    title: '강남구 미래인재 스마트시티',
    subtitle: '안전한 나의 친구',
    type: '상상 더하기 체험',
    user: 'ahnji1',
    timestamp: '2024-10-25',
    heartRate: 32,
  },
  {
    idx: 11,
    imgUrl: 'https://placehold.co/150',
    title: '강남구 미래인재 스마트시티',
    subtitle: '안전한 나의 친구',
    type: '문제해결 체험',
    user: 'ahnji1',
    timestamp: '2024-10-25',
    heartRate: 1,
  },
  {
    idx: 12,
    imgUrl: 'https://placehold.co/150',
    title: '강남구 미래인재 스마트시티',
    subtitle: '안전한 나의 친구',
    type: '문제해결 체험',
    user: 'ahnji1',
    timestamp: '2024-10-25',
    heartRate: 0,
  },
  {
    idx: 13,
    imgUrl: 'https://placehold.co/150',
    title: '강남구 미래인재 스마트시티',
    subtitle: '안전한 나의 친구',
    type: '문제해결 체험',
    user: 'ahnji1',
    timestamp: '2024-10-25',
    heartRate: 10,
  },
  {
    idx: 14,
    imgUrl: 'https://placehold.co/150',
    title: '강남구 미래인재 스마트시티',
    subtitle: '안전한 나의 친구',
    type: '문제해결 체험',
    user: 'ahnji1',
    timestamp: '2024-10-25',
    heartRate: 10,
  },
  {
    idx: 15,
    imgUrl: 'https://placehold.co/150',
    title: '강남구 미래인재 스마트시티',
    subtitle: '안전한 나의 친구',
    type: '문제해결 체험',
    user: 'ahnji1',
    timestamp: '2024-10-25',
    heartRate: 10,
  },
  {
    idx: 16,
    imgUrl: 'https://placehold.co/150',
    title: '강남구 미래인재 스마트시티',
    subtitle: '안전한 나의 친구',
    type: '문제해결 체험',
    user: 'ahnji1',
    timestamp: '2024-10-25',
    heartRate: 2,
  },
  {
    idx: 17,
    imgUrl: 'https://placehold.co/150',
    title: '강남구 미래인재 스마트시티',
    subtitle: '안전한 나의 친구',
    type: 'AI 간편 체험',
    user: 'ahnji1',
    timestamp: '2024-10-25',
    heartRate: 11,
  },
  {
    idx: 18,
    imgUrl: 'https://placehold.co/150',
    title: '강남구 미래인재 스마트시티',
    subtitle: '안전한 나의 친구',
    type: '웹툰 생성 체험',
    user: 'ahnji1',
    timestamp: '2024-10-25',
    heartRate: 2,
  }
]

export const projectList: Project[] = [
  {
    idx: 1,
    titleKo: '플래닛파크 문제해결 프로젝트',
    titleEn: 'eco friendly project',
    subTitle: 'test',
    imgUrl: 'https://placehold.co/150',
    hash: ['#스마트시티','#미래도시','#아이디어','#창의사고력'],
    type: 'AI 간편 체험',
    story: '안녕하세요. 저는 2100년 스마트시티에 살고 있는 중학생 이기쁨, 이소망이에요. 우리가 살고있는 미래 스마트시티 강남은 모두가 행복한 도시예요! 하지만 기술은 점점 더 발전하고 생태환경도 점점 더 변해가면서 하루가 다르게 변해가는 강남의 모습을 보면서 "어떻게 하면 모두가 조금 더 살기 좋은 도시가 될 수 없을까?" 고민을 시작해보게 됐죠! 여러분 좋은 아이디어 없을까요? 저에게 알려주세요!',
    timeStamp: '2024-10-25',
  },
  {
    idx: 2,
    titleKo: '플래닛파크 문제해결 프로젝트',
    titleEn: 'eco friendly project',
    subTitle: 'test',
    imgUrl: 'https://placehold.co/150',
    hash: ['#스마트시티','#미래도시','#아이디어','#창의사고력'],
    type: '문제해결 체험',
    story: '안녕하세요. 저는 2100년 스마트시티에 살고 있는 중학생 이기쁨, 이소망이에요. 우리가 살고있는 미래 스마트시티 강남은 모두가 행복한 도시예요! 하지만 기술은 점점 더 발전하고 생태환경도 점점 더 변해가면서 하루가 다르게 변해가는 강남의 모습을 보면서 "어떻게 하면 모두가 조금 더 살기 좋은 도시가 될 수 없을까?" 고민을 시작해보게 됐죠! 여러분 좋은 아이디어 없을까요? 저에게 알려주세요!',
    timeStamp: '2024-10-25',
  },
  {
    idx: 3,
    titleKo: '우주도시 문제해결 프로젝트',
    titleEn: 'build space city project',
    subTitle: 'test',
    imgUrl: 'https://placehold.co/150',
    hash: ['#스마트시티','#미래도시','#아이디어','#창의사고력'],
    type: '상상 더하기 체험',
    story: '안녕하세요. 저는 2100년 스마트시티에 살고 있는 중학생 이기쁨, 이소망이에요. 우리가 살고있는 미래 스마트시티 강남은 모두가 행복한 도시예요! 하지만 기술은 점점 더 발전하고 생태환경도 점점 더 변해가면서 하루가 다르게 변해가는 강남의 모습을 보면서 "어떻게 하면 모두가 조금 더 살기 좋은 도시가 될 수 없을까?" 고민을 시작해보게 됐죠! 여러분 좋은 아이디어 없을까요? 저에게 알려주세요!',
    timeStamp: '2024-10-23',
  },
  {
    idx: 4,
    titleKo: '플래닛파크 문제해결 프로젝트',
    titleEn: 'eco friendly project',
    subTitle: 'test',
    imgUrl: 'https://placehold.co/150',
    hash: ['#스마트시티','#미래도시','#아이디어','#창의사고력'],
    type: '상상 더하기 체험',
    story: '안녕하세요. 저는 2100년 스마트시티에 살고 있는 중학생 이기쁨, 이소망이에요. 우리가 살고있는 미래 스마트시티 강남은 모두가 행복한 도시예요! 하지만 기술은 점점 더 발전하고 생태환경도 점점 더 변해가면서 하루가 다르게 변해가는 강남의 모습을 보면서 "어떻게 하면 모두가 조금 더 살기 좋은 도시가 될 수 없을까?" 고민을 시작해보게 됐죠! 여러분 좋은 아이디어 없을까요? 저에게 알려주세요!',
    timeStamp: '2024-10-24',
  },
  {
    idx: 5,
    titleKo: '플래닛파크 문제해결 프로젝트',
    titleEn: 'eco friendly project',
    subTitle: 'test',
    imgUrl: 'https://placehold.co/150',
    hash: ['#스마트시티','#미래도시','#아이디어','#창의사고력'],
    type: '문제해결 체험',
    story: '안녕하세요. 저는 2100년 스마트시티에 살고 있는 중학생 이기쁨, 이소망이에요. 우리가 살고있는 미래 스마트시티 강남은 모두가 행복한 도시예요! 하지만 기술은 점점 더 발전하고 생태환경도 점점 더 변해가면서 하루가 다르게 변해가는 강남의 모습을 보면서 "어떻게 하면 모두가 조금 더 살기 좋은 도시가 될 수 없을까?" 고민을 시작해보게 됐죠! 여러분 좋은 아이디어 없을까요? 저에게 알려주세요!',
    timeStamp: '2024-10-22',
  },
  {
    idx: 6,
    titleKo: '플래닛파크 문제해결 프로젝트',
    titleEn: 'eco friendly project',
    subTitle: 'test',
    imgUrl: 'https://placehold.co/150',
    type: '상상 더하기 체험',
    hash: ['#스마트시티','#미래도시','#아이디어','#창의사고력'],
    story: '안녕하세요. 저는 2100년 스마트시티에 살고 있는 중학생 이기쁨, 이소망이에요. 우리가 살고있는 미래 스마트시티 강남은 모두가 행복한 도시예요! 하지만 기술은 점점 더 발전하고 생태환경도 점점 더 변해가면서 하루가 다르게 변해가는 강남의 모습을 보면서 "어떻게 하면 모두가 조금 더 살기 좋은 도시가 될 수 없을까?" 고민을 시작해보게 됐죠! 여러분 좋은 아이디어 없을까요? 저에게 알려주세요!',
    timeStamp: '2024-10-21',
  },
  {
    idx: 7,
    titleKo: '플래닛파크 문제해결 프로젝트',
    titleEn: 'eco friendly project',
    subTitle: 'test',
    imgUrl: 'https://placehold.co/150',
    hash: ['#스마트시티','#미래도시','#아이디어','#창의사고력'],
    type: '웹툰 생성 체험',
    story: '안녕하세요. 저는 2100년 스마트시티에 살고 있는 중학생 이기쁨, 이소망이에요. 우리가 살고있는 미래 스마트시티 강남은 모두가 행복한 도시예요! 하지만 기술은 점점 더 발전하고 생태환경도 점점 더 변해가면서 하루가 다르게 변해가는 강남의 모습을 보면서 "어떻게 하면 모두가 조금 더 살기 좋은 도시가 될 수 없을까?" 고민을 시작해보게 됐죠! 여러분 좋은 아이디어 없을까요? 저에게 알려주세요!',
    timeStamp: '2024-10-20',
  },
  {
    idx: 8,
    titleKo: '플래닛파크 문제해결 프로젝트',
    titleEn: 'eco friendly project',
    subTitle: 'test',
    imgUrl: 'https://placehold.co/150',
    hash: ['#스마트시티','#미래도시','#아이디어','#창의사고력'],
    type: '문제해결 체험',
    story: '안녕하세요. 저는 2100년 스마트시티에 살고 있는 중학생 이기쁨, 이소망이에요. 우리가 살고있는 미래 스마트시티 강남은 모두가 행복한 도시예요! 하지만 기술은 점점 더 발전하고 생태환경도 점점 더 변해가면서 하루가 다르게 변해가는 강남의 모습을 보면서 "어떻게 하면 모두가 조금 더 살기 좋은 도시가 될 수 없을까?" 고민을 시작해보게 됐죠! 여러분 좋은 아이디어 없을까요? 저에게 알려주세요!',
    timeStamp: '2024-10-20',
  },
  {
    idx: 9,
    titleKo: '플래닛파크 문제해결 프로젝트',
    titleEn: 'eco friendly project',
    subTitle: 'test',
    imgUrl: 'https://placehold.co/150',
    hash: ['#스마트시티','#미래도시','#아이디어','#창의사고력'],
    type: '웹툰 생성 체험',
    story: '안녕하세요. 저는 2100년 스마트시티에 살고 있는 중학생 이기쁨, 이소망이에요. 우리가 살고있는 미래 스마트시티 강남은 모두가 행복한 도시예요! 하지만 기술은 점점 더 발전하고 생태환경도 점점 더 변해가면서 하루가 다르게 변해가는 강남의 모습을 보면서 "어떻게 하면 모두가 조금 더 살기 좋은 도시가 될 수 없을까?" 고민을 시작해보게 됐죠! 여러분 좋은 아이디어 없을까요? 저에게 알려주세요!',
    timeStamp: '2024-10-25',
  },
  {
    idx: 10,
    titleKo: '플래닛파크 문제해결 프로젝트',
    titleEn: 'eco friendly project',
    subTitle: 'test',
    imgUrl: 'https://placehold.co/150',
    hash: ['#스마트시티','#미래도시','#아이디어','#창의사고력'],
    type: '웹툰 생성 체험',
    story: '안녕하세요. 저는 2100년 스마트시티에 살고 있는 중학생 이기쁨, 이소망이에요. 우리가 살고있는 미래 스마트시티 강남은 모두가 행복한 도시예요! 하지만 기술은 점점 더 발전하고 생태환경도 점점 더 변해가면서 하루가 다르게 변해가는 강남의 모습을 보면서 "어떻게 하면 모두가 조금 더 살기 좋은 도시가 될 수 없을까?" 고민을 시작해보게 됐죠! 여러분 좋은 아이디어 없을까요? 저에게 알려주세요!',
    timeStamp: '2024-10-25',
  },
  {
    idx: 11,
    titleKo: '플래닛파크 문제해결 프로젝트',
    titleEn: 'eco friendly project',
    subTitle: 'test',
    imgUrl: 'https://placehold.co/150',
    hash: ['#스마트시티','#미래도시','#아이디어','#창의사고력'],
    type: '문제해결 체험',
    story: '안녕하세요. 저는 2100년 스마트시티에 살고 있는 중학생 이기쁨, 이소망이에요. 우리가 살고있는 미래 스마트시티 강남은 모두가 행복한 도시예요! 하지만 기술은 점점 더 발전하고 생태환경도 점점 더 변해가면서 하루가 다르게 변해가는 강남의 모습을 보면서 "어떻게 하면 모두가 조금 더 살기 좋은 도시가 될 수 없을까?" 고민을 시작해보게 됐죠! 여러분 좋은 아이디어 없을까요? 저에게 알려주세요!',
    timeStamp: '2024-10-19',
  },
  {
    idx: 12,
    titleKo: '우주도시 문제해결 프로젝트',
    titleEn: 'eco friendly project',
    subTitle: 'test',
    imgUrl: 'https://placehold.co/150',
    hash: ['#스마트시티','#미래도시','#아이디어','#창의사고력'],
    type: '웹툰 생성 체험',
    story: '안녕하세요. 저는 2100년 스마트시티에 살고 있는 중학생 이기쁨, 이소망이에요. 우리가 살고있는 미래 스마트시티 강남은 모두가 행복한 도시예요! 하지만 기술은 점점 더 발전하고 생태환경도 점점 더 변해가면서 하루가 다르게 변해가는 강남의 모습을 보면서 "어떻게 하면 모두가 조금 더 살기 좋은 도시가 될 수 없을까?" 고민을 시작해보게 됐죠! 여러분 좋은 아이디어 없을까요? 저에게 알려주세요!',
    timeStamp: '2024-09-25',
  },
  {
    idx: 13,
    titleKo: '플래닛공원 문제해결 프로젝트',
    titleEn: 'eco friendly project',
    subTitle: 'test',
    imgUrl: 'https://placehold.co/150',
    hash: ['#스마트시티','#미래도시','#아이디어','#창의사고력'],
    type: '웹툰 생성 체험',
    story: '안녕하세요. 저는 2100년 스마트시티에 살고 있는 중학생 이기쁨, 이소망이에요. 우리가 살고있는 미래 스마트시티 강남은 모두가 행복한 도시예요! 하지만 기술은 점점 더 발전하고 생태환경도 점점 더 변해가면서 하루가 다르게 변해가는 강남의 모습을 보면서 "어떻게 하면 모두가 조금 더 살기 좋은 도시가 될 수 없을까?" 고민을 시작해보게 됐죠! 여러분 좋은 아이디어 없을까요? 저에게 알려주세요!',
    timeStamp: '2024-12-11',
  },
  {
    idx: 14,
    titleKo: '플래닛공원 문제해결 프로젝트',
    titleEn: 'eco friendly project',
    subTitle: 'test',
    imgUrl: 'https://placehold.co/150',
    hash: ['#스마트시티','#미래도시','#아이디어','#창의사고력'],
    type: '문제해결 체험',
    story: '안녕하세요. 저는 2100년 스마트시티에 살고 있는 중학생 이기쁨, 이소망이에요. 우리가 살고있는 미래 스마트시티 강남은 모두가 행복한 도시예요! 하지만 기술은 점점 더 발전하고 생태환경도 점점 더 변해가면서 하루가 다르게 변해가는 강남의 모습을 보면서 "어떻게 하면 모두가 조금 더 살기 좋은 도시가 될 수 없을까?" 고민을 시작해보게 됐죠! 여러분 좋은 아이디어 없을까요? 저에게 알려주세요!',
    timeStamp: '2024-10-25',
  },
  {
    idx: 15,
    titleKo: '플래닛파크 문제해결 프로젝트',
    titleEn: 'eco friendly project',
    subTitle: 'test',
    imgUrl: 'https://placehold.co/150',
    hash: ['#스마트시티','#미래도시','#아이디어','#창의사고력'],
    type: '웹툰 생성 체험',
    story: '안녕하세요. 저는 2100년 스마트시티에 살고 있는 중학생 이기쁨, 이소망이에요. 우리가 살고있는 미래 스마트시티 강남은 모두가 행복한 도시예요! 하지만 기술은 점점 더 발전하고 생태환경도 점점 더 변해가면서 하루가 다르게 변해가는 강남의 모습을 보면서 "어떻게 하면 모두가 조금 더 살기 좋은 도시가 될 수 없을까?" 고민을 시작해보게 됐죠! 여러분 좋은 아이디어 없을까요? 저에게 알려주세요!',
    timeStamp: '2024-10-23',
  },
  {
    idx: 16,
    titleKo: '플래닛파크 문제해결 프로젝트',
    titleEn: 'eco friendly project',
    subTitle: 'test',
    imgUrl: 'https://placehold.co/150',
    hash: ['#스마트시티','#미래도시','#아이디어','#창의사고력'],
    type: '웹툰 생성 체험',
    story: '안녕하세요. 저는 2100년 스마트시티에 살고 있는 중학생 이기쁨, 이소망이에요. 우리가 살고있는 미래 스마트시티 강남은 모두가 행복한 도시예요! 하지만 기술은 점점 더 발전하고 생태환경도 점점 더 변해가면서 하루가 다르게 변해가는 강남의 모습을 보면서 "어떻게 하면 모두가 조금 더 살기 좋은 도시가 될 수 없을까?" 고민을 시작해보게 됐죠! 여러분 좋은 아이디어 없을까요? 저에게 알려주세요!',
    timeStamp: '2024-10-21',
  },
  {
    idx: 17,
    titleKo: '플래닛파크 문제해결 프로젝트',
    titleEn: 'eco friendly project',
    subTitle: 'test',
    imgUrl: 'https://placehold.co/150',
    hash: ['#스마트시티','#미래도시','#아이디어','#창의사고력'],
    type: '문제해결 체험',
    story: '안녕하세요. 저는 2100년 스마트시티에 살고 있는 중학생 이기쁨, 이소망이에요. 우리가 살고있는 미래 스마트시티 강남은 모두가 행복한 도시예요! 하지만 기술은 점점 더 발전하고 생태환경도 점점 더 변해가면서 하루가 다르게 변해가는 강남의 모습을 보면서 "어떻게 하면 모두가 조금 더 살기 좋은 도시가 될 수 없을까?" 고민을 시작해보게 됐죠! 여러분 좋은 아이디어 없을까요? 저에게 알려주세요!',
    timeStamp: '2024-10-25',
  },
  {
    idx: 18,
    titleKo: '플래닛파크 문제해결 프로젝트',
    titleEn: 'eco friendly project',
    subTitle: 'test',
    imgUrl: 'https://placehold.co/150',
    hash: ['#스마트시티','#미래도시','#아이디어','#창의사고력'],
    type: 'AI 간편 체험',
    story: '안녕하세요. 저는 2100년 스마트시티에 살고 있는 중학생 이기쁨, 이소망이에요. 우리가 살고있는 미래 스마트시티 강남은 모두가 행복한 도시예요! 하지만 기술은 점점 더 발전하고 생태환경도 점점 더 변해가면서 하루가 다르게 변해가는 강남의 모습을 보면서 "어떻게 하면 모두가 조금 더 살기 좋은 도시가 될 수 없을까?" 고민을 시작해보게 됐죠! 여러분 좋은 아이디어 없을까요? 저에게 알려주세요!',
    timeStamp: '2024-10-25',
  },
]

export const activeClass = "font-bold bg-[#FFE552] w-10 p-2 aspect-square rounded-full";
export const inactiveClass = "text-gray-600";



